git clone https://github.com/maidsafe/maidsafe.github.io.git
git clone https://github.com/maidsafe/routing.git
git clone https://github.com/maidsafe/crust.git
git clone https://github.com/maidsafe/rust-utp.git
git clone https://github.com/maidsafe/safe_vault.git
git clone https://github.com/maidsafe/safe_launcher.git
git clone https://github.com/maidsafe/safe_ffi.git
git clone https://github.com/maidsafe/self_encryption.git
git clone https://github.com/maidsafe/safe_dns.git
git clone https://github.com/maidsafe/safe_nfs.git
git clone https://github.com/maidsafe/safe_core.git
git clone https://github.com/maidsafe/message_filter.git
git clone https://github.com/maidsafe/accumulator.git
git clone https://github.com/maidsafe/xor_name.git
git clone https://github.com/maidsafe/maidsafe_utilities.git
git clone https://github.com/maidsafe/lru_time_cache.git
git clone https://github.com/maidsafe/drive.git
git clone https://github.com/maidsafe/kademlia_routing_table.git
git clone https://github.com/maidsafe/QA.git
git clone https://github.com/maidsafe/rfcs.git

